Script to parse ACL Anthology bibtex. Results of the parsing saved in pickle format for faster loading.

In [2]:
import bibtexparser
import pandas as pd

Takes approximately 6 minutes for 57k papers (papers from 2020 to today).

In [ ]:
with open('../data/acl_anthology.bib') as bibtex_file:  ## acl_anthology.bib must be downloaded from the ACL Anthology website and placed in the ../data directory for parsing
    bib_database = bibtexparser.load(bibtex_file)

In [4]:
# Example of retrieving a specific entry
bib_database.entries_dict['chen-2025-research']

{'abstract': 'This is a position paper for my research, including my research interests, my views about Spoken dialogue system (SDS) research and suggested topics for discussion.',
 'pages': '1--3',
 'url': 'https://aclanthology.org/2025.yrrsds-1.1/',
 'publisher': 'Association for Computational Linguistics',
 'address': 'Avignon, France',
 'year': '2025',
 'month': 'August',
 'booktitle': "Proceedings of the 21st Workshop of Young Researchers' Roundtable on Spoken Dialogue Systems",
 'editor': 'Whetten, Ryan  and\nSucal, Virgile  and\nNgo, Anh  and\nChalamalasetti, Kranti  and\nInoue, Koji  and\nCimino, Gaetano  and\nYang, Zachary  and\nZenimoto, Yuki  and\nRodriguez, Ricardo',
 'author': 'Chen, Ben',
 'title': 'Research on {LLM}s-Empowered Conversational {AI} for Sustainable Behaviour Change',
 'ENTRYTYPE': 'inproceedings',
 'ID': 'chen-2025-research'}

In [18]:
print("Number of Papers:", len(bib_database.entries_dict.keys()))

Number of Papers: 57270

In [19]:
# For first 3 keys in bib_database.entries_dict, print the key and title, abstract
for i, key in enumerate(bib_database.entries_dict.keys()):
    if i >= 3:
        break
    entry = bib_database.entries_dict[key]
    print(f"Key: {key}")
    print(f"Title: {entry.get('title', 'N/A')}")
    print(f"Abstract: {entry.get('abstract', 'N/A')}")
    print()

Key: yrrsds-2025-1
Title: Proceedings of the 21st Workshop of Young Researchers' Roundtable on Spoken Dialogue Systems
Abstract: N/A

Key: chen-2025-research
Title: Research on {LLM}s-Empowered Conversational {AI} for Sustainable Behaviour Change
Abstract: This is a position paper for my research, including my research interests, my views about Spoken dialogue system (SDS) research and suggested topics for discussion.

Key: levandovsky-2025-deep
Title: Deep Reinforcement Learning of {LLM}s​ using {RLHF}
Abstract: My main research interests lies in the application of Reinforcement Learning (RL) alignment of LLMs in human robot dialogue. More specifically, my latest research aims to use RL alignment as an efficient training regime to train a newly initialized tiny LM to behave like a toddler. Previous research expresses the difficulty of building a robust tiny LM with an educated adult level understanding. Our hypothesis is that the cognitive barrier to train a tiny LM to at-least behave as a child is achievable with a very small number of parameters especially if training efficiently using RL LLM training regime. My interests also extend to apply RL to LLM training for dialogue management and planning.

In [25]:
# Load the dictionary into a pandas dataframe
acl_bibliography_df = pd.DataFrame.from_dict(bib_database.entries_dict, orient='index')

In [26]:
acl_bibliography_df.head(2)

,url,publisher,address,year,month,editor,title,ENTRYTYPE,ID,abstract,pages,booktitle,author,isbn,doi,volume,journal,language,number
yrrsds-2025-1,https://aclanthology.org/2025.yrrsds-1.0/,Association for Computational Linguistics,"Avignon, France",2025,August,"Whetten, Ryan and\nSucal, Virgile and\nNgo, ...",Proceedings of the 21st Workshop of Young Rese...,proceedings,yrrsds-2025-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chen-2025-research,https://aclanthology.org/2025.yrrsds-1.1/,Association for Computational Linguistics,"Avignon, France",2025,August,"Whetten, Ryan and\nSucal, Virgile and\nNgo, ...",Research on {LLM}s-Empowered Conversational {A...,inproceedings,chen-2025-research,"This is a position paper for my research, incl...",1--3,Proceedings of the 21st Workshop of Young Rese...,"Chen, Ben",NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Scorporate the index to make it a column
acl_bibliography_df.reset_index(inplace=True)
acl_bibliography_df.rename(columns={'index': 'bib_key'}, inplace=True)

In [28]:
acl_bibliography_df.head(2)

,bib_key,url,publisher,address,year,month,editor,title,ENTRYTYPE,ID,abstract,pages,booktitle,author,isbn,doi,volume,journal,language,number
0,yrrsds-2025-1,https://aclanthology.org/2025.yrrsds-1.0/,Association for Computational Linguistics,"Avignon, France",2025,August,"Whetten, Ryan and\nSucal, Virgile and\nNgo, ...",Proceedings of the 21st Workshop of Young Rese...,proceedings,yrrsds-2025-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chen-2025-research,https://aclanthology.org/2025.yrrsds-1.1/,Association for Computational Linguistics,"Avignon, France",2025,August,"Whetten, Ryan and\nSucal, Virgile and\nNgo, ...",Research on {LLM}s-Empowered Conversational {A...,inproceedings,chen-2025-research,"This is a position paper for my research, incl...",1--3,Proceedings of the 21st Workshop of Young Rese...,"Chen, Ben",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
acl_bibliography_df.to_pickle("../data/acl_bibliography.pkl")